### ISSUE TITLE
我感觉还不完善吧，bugg

### ISSUE THREAD

**Issue by cdpenggod** [YvanLiu/HeartBeatsPlugin#1]
你这个我确实感觉挺新鲜，但是我把手指移开后它不应该显示0次吗？为什么还会有数据？控制台虽然也log出提示说需要手指，但后面就继续log一堆数据，无限重复这个，问题是我还没吧手放上去啊，这样我都感觉像假数据了…希望你能改掉这个bug，我用的7，系统是10.0

**Comment by YvanLiu** [comment]
嗯，我之前是打算当做一个demo来写的，并没有封装的那么详细，非常感谢你提出的问题，这个确实是我没考虑到，

**Comment by sauchye** [comment]
So cool，感觉波动比较大，从55到66再到100

**Comment by YvanLiu** [comment]
@sauchye 是的，这也是我正在要解决的问题，如果有更好的方法麻烦告知。
